before_commands:
  - "composer self-update"
  - "composer update"

filter:
  excluded_paths: ["vendor/*"]

tools:
  php_code_coverage:
    enabled: true
    test_command: phpunit --configuration travis-phpunit.xml.dist
    filter:
      paths: ["src/*"]
      excluded_paths: ["tests/*", "vendor/*"]
  php_cpd:
    enabled: true
    excluded_dirs: ["vendor"]
  php_loc:
    enabled: true
    command: phploc
    names:
      - '*.php'
    excluded_dirs: ["vendor"]
  php_mess_detector: true
  php_pdepend:
    enabled: true
    excluded_dirs: ["vendor"]
  php_analyzer:
    enabled: true
    filter:
      paths: ["src/", "tests/"]
  sensiolabs_security_checker: true
  external_code_coverage: true
