---
language: php
sudo: false
branches:
  only:
    - master
php:
  - "7.2"

before_script:
  - pecl install ds
  - composer self-update
  - composer install --no-progress --no-suggest
script:
  - vendor/bin/labrador-cs src/ test/
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
